package com.auction.sale.domain.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.userName
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.password
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userName
     *
     * @return the value of t_user_info.userName
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userName
     *
     * @param username the value for t_user_info.userName
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     *
     * @mbg.generated Sat Nov 27 15:24:54 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}